create table public.todoist_data (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  is_completed boolean not null default false
);
insert into public.todoist_data (title, is_completed) values
  ('Buy groceries', false),
  ('Review iOS app wireframes', false),
  ('Call the dentist', true),
  ('Pay electricity bill', false),
  ('Finish FastAPI setup', true),
  ('Clean workspace', false),
  ('Read Supabase docs', true),
  ('Backup project files', false),
  ('Plan weekly tasks', false),
  ('Update app icons', true),
  ('Test login screen', false),
  ('Write CRUD API notes', false),
  ('Check database table', true),
  ('Refactor todo list view', false),
  ('Prepare meeting agenda', false),
  ('Send progress update', true),
  ('Fix empty state UI', false),
  ('Create sample todo data', true),
  ('Organize Downloads folder', false),
  ('Practice SwiftUI navigation', false),
  ('Verify API response format', true),
  ('Add loading indicator', false),
  ('Check iOS simulator build', false),
  ('Draft README file', true),
  ('Review error handling', false),
  ('Update environment variables', true),
  ('Create delete confirmation', false),
  ('Test completed task toggle', false),
  ('Sync Supabase schema', true),
  ('Plan tomorrow schedule', false);